name: Deploy FullStackApp
on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - run: docker build -t jmw0625/frontend -f ./frontend/Dockerfile.dev ./frontend
      - run: docker run -e CI=true jmw0625/frontend npm test

      - run: docker build -t jwm0625/frontend ./frontend
      - run: docker build -t jwm0625/nginx ./nginx
      - run: docker build -t jwm0625/backend ./backend

      - run: docker push jmw0625/frontend
      - run: docker push jmw0625/nginx
      - run: docker push jmw0625/backend

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-fullstack-app
          environment_name: Docker-fullstack-app-env
          existing_bucket_name: elasticbeanstalk-ap-northeast-2-406474718927
          region: ap-northeast-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip

